//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan360.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plan360Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plan360Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plan360.UI.Resources.Plan360Strings", typeof(Plan360Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string ACTION_Activate {
            get {
                return ResourceManager.GetString("ACTION_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Todos-.
        /// </summary>
        public static string ACTION_All {
            get {
                return ResourceManager.GetString("ACTION_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string ACTION_Create {
            get {
                return ResourceManager.GetString("ACTION_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string ACTION_Deactivate {
            get {
                return ResourceManager.GetString("ACTION_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ACTION_Edit {
            get {
                return ResourceManager.GetString("ACTION_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma operação ?.
        /// </summary>
        public static string ACTION_OperationConfirm {
            get {
                return ResourceManager.GetString("ACTION_OperationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrizar.
        /// </summary>
        public static string ACTION_Parametrize {
            get {
                return ResourceManager.GetString("ACTION_Parametrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string ACTION_Remove {
            get {
                return ResourceManager.GetString("ACTION_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Selecione-.
        /// </summary>
        public static string ACTION_Select {
            get {
                return ResourceManager.GetString("ACTION_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string ACTION_Update {
            get {
                return ResourceManager.GetString("ACTION_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representante.
        /// </summary>
        public static string AGENT {
            get {
                return ResourceManager.GetString("AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Agente.
        /// </summary>
        public static string AGENT_Code {
            get {
                return ResourceManager.GetString("AGENT_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código SAP.
        /// </summary>
        public static string AGENT_ErpCode {
            get {
                return ResourceManager.GetString("AGENT_ErpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes.
        /// </summary>
        public static string AGENT_List {
            get {
                return ResourceManager.GetString("AGENT_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função.
        /// </summary>
        public static string AGENT_Role {
            get {
                return ResourceManager.GetString("AGENT_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string BRAND {
            get {
                return ResourceManager.GetString("BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Marca.
        /// </summary>
        public static string BRAND_Create {
            get {
                return ResourceManager.GetString("BRAND_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Marca.
        /// </summary>
        public static string BRAND_Edit {
            get {
                return ResourceManager.GetString("BRAND_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string BRAND_List {
            get {
                return ResourceManager.GetString("BRAND_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclos.
        /// </summary>
        public static string CALENDAR_List {
            get {
                return ResourceManager.GetString("CALENDAR_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado Por.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        public static string Ean {
            get {
                return ResourceManager.GetString("Ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazio.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fim.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string ENTERPRISE {
            get {
                return ResourceManager.GetString("ENTERPRISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Empresa.
        /// </summary>
        public static string ENTERPRISE_Create {
            get {
                return ResourceManager.GetString("ENTERPRISE_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Empresa.
        /// </summary>
        public static string ENTERPRISE_Edit {
            get {
                return ResourceManager.GetString("ENTERPRISE_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        public static string ENTERPRISE_List {
            get {
                return ResourceManager.GetString("ENTERPRISE_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        public static string ENTITY {
            get {
                return ResourceManager.GetString("ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string ENTITY_Enterprise {
            get {
                return ResourceManager.GetString("ENTITY_Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        public static string ENTITY_List {
            get {
                return ResourceManager.GetString("ENTITY_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadado.
        /// </summary>
        public static string ENTITY_Metadata {
            get {
                return ResourceManager.GetString("ENTITY_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadados.
        /// </summary>
        public static string ENTITY_Metadatas {
            get {
                return ResourceManager.GetString("ENTITY_Metadatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano.
        /// </summary>
        public static string ENTITY_Plan {
            get {
                return ResourceManager.GetString("ENTITY_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade Vazia.
        /// </summary>
        public static string ENTITY_SelectEntity {
            get {
                return ResourceManager.GetString("ENTITY_SelectEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo de plano.
        /// </summary>
        public static string ENTITY_Template {
            get {
                return ResourceManager.GetString("ENTITY_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo.
        /// </summary>
        public static string ENTITYMETADATA_Field {
            get {
                return ResourceManager.GetString("ENTITYMETADATA_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string ENTITYMETADATA_Value {
            get {
                return ResourceManager.GetString("ENTITYMETADATA_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não identificado; Verifique se os campos foram preenchidos corretamente e tente novamente..
        /// </summary>
        public static string ERROR_GenericUpdate {
            get {
                return ResourceManager.GetString("ERROR_GenericUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor informe um valor entre {1} e {2}.
        /// </summary>
        public static string ERROR_RANGE {
            get {
                return ResourceManager.GetString("ERROR_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        public static string ERROR_Required {
            get {
                return ResourceManager.GetString("ERROR_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} possúi um tamanho máximo de {1} caracteres.
        /// </summary>
        public static string ERROR_Size {
            get {
                return ResourceManager.GetString("ERROR_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro interno! O Plano violou a consistência de dados, informe o suporte o erro {0}.
        /// </summary>
        public static string INTERNAL_INCONSISTENCE {
            get {
                return ResourceManager.GetString("INTERNAL_INCONSISTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceConfig.
        /// </summary>
        public static string InvoiceConfig {
            get {
                return ResourceManager.GetString("InvoiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregado.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        public static string MENU_Administration {
            get {
                return ResourceManager.GetString("MENU_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string MENU_Configuration {
            get {
                return ResourceManager.GetString("MENU_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MENU_Dashboard {
            get {
                return ResourceManager.GetString("MENU_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados.
        /// </summary>
        public static string MENU_Data {
            get {
                return ResourceManager.GetString("MENU_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        public static string MENU_Help {
            get {
                return ResourceManager.GetString("MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integração.
        /// </summary>
        public static string MENU_Integration {
            get {
                return ResourceManager.GetString("MENU_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planos.
        /// </summary>
        public static string MENU_Plans {
            get {
                return ResourceManager.GetString("MENU_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        public static string MENU_Reports {
            get {
                return ResourceManager.GetString("MENU_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificado Por.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem dados para exibir.
        /// </summary>
        public static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Preenchido.
        /// </summary>
        public static string NotFill {
            get {
                return ResourceManager.GetString("NotFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ger. Responsável.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string PAGINATION_Of {
            get {
                return ResourceManager.GetString("PAGINATION_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string PAGINATION_Page {
            get {
                return ResourceManager.GetString("PAGINATION_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string PAGINATION_Total {
            get {
                return ResourceManager.GetString("PAGINATION_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem agentes selecionados. .
        /// </summary>
        public static string PLAN_AgentsEmpty {
            get {
                return ResourceManager.GetString("PLAN_AgentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar a empresa irá resetar todos os dados do plano, deseja continuar?.
        /// </summary>
        public static string PLAN_ConfirmEnterpriseChange {
            get {
                return ResourceManager.GetString("PLAN_ConfirmEnterpriseChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd.
        /// </summary>
        public static string PLAN_Count {
            get {
                return ResourceManager.GetString("PLAN_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Plano.
        /// </summary>
        public static string PLAN_Create {
            get {
                return ResourceManager.GetString("PLAN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Plano.
        /// </summary>
        public static string PLAN_Detail {
            get {
                return ResourceManager.GetString("PLAN_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Plano.
        /// </summary>
        public static string PLAN_Edit {
            get {
                return ResourceManager.GetString("PLAN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planos.
        /// </summary>
        public static string PLAN_List {
            get {
                return ResourceManager.GetString("PLAN_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros dados....
        /// </summary>
        public static string PLAN_OtherData {
            get {
                return ResourceManager.GetString("PLAN_OtherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietário.
        /// </summary>
        public static string PLAN_Owner {
            get {
                return ResourceManager.GetString("PLAN_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Plano.
        /// </summary>
        public static string PLAN_Remove {
            get {
                return ResourceManager.GetString("PLAN_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo excluir este plano?.
        /// </summary>
        public static string PLAN_Remove_Confirm {
            get {
                return ResourceManager.GetString("PLAN_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O plano não pode ser excluido pois já existem faturamentos realizados do mesmo.
        /// </summary>
        public static string PLAN_Remove_InUse {
            get {
                return ResourceManager.GetString("PLAN_Remove_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Plano foi excluído com sucesso.
        /// </summary>
        public static string PLAN_Remove_Success {
            get {
                return ResourceManager.GetString("PLAN_Remove_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação foi concluída com sucesso! Deseja ir para a parametrização?.
        /// </summary>
        public static string PLAN_SaveRedirect {
            get {
                return ResourceManager.GetString("PLAN_SaveRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um metadado para continuar.
        /// </summary>
        public static string PLAN_SearchEntityMetadataEmpty {
            get {
                return ResourceManager.GetString("PLAN_SearchEntityMetadataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Representantes.
        /// </summary>
        public static string PLAN_SelectAgentsCaption {
            get {
                return ResourceManager.GetString("PLAN_SelectAgentsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representantes Selecionados.
        /// </summary>
        public static string PLAN_SelectedAgentsCaption {
            get {
                return ResourceManager.GetString("PLAN_SelectedAgentsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem agentes selecionados.
        /// </summary>
        public static string PLAN_SelectedAgentsEmpty {
            get {
                return ResourceManager.GetString("PLAN_SelectedAgentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades Selecionadas.
        /// </summary>
        public static string PLAN_SelectedEntitiesCaption {
            get {
                return ResourceManager.GetString("PLAN_SelectedEntitiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos Selecionados.
        /// </summary>
        public static string PLAN_SelectedProductsCaption {
            get {
                return ResourceManager.GetString("PLAN_SelectedProductsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Entidades.
        /// </summary>
        public static string PLAN_SelectEntitiesCaption {
            get {
                return ResourceManager.GetString("PLAN_SelectEntitiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Produtos.
        /// </summary>
        public static string PLAN_SelectProducts {
            get {
                return ResourceManager.GetString("PLAN_SelectProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        public static string PLAN_Step1 {
            get {
                return ResourceManager.GetString("PLAN_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes.
        /// </summary>
        public static string PLAN_Step2 {
            get {
                return ResourceManager.GetString("PLAN_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        public static string PLAN_Step3 {
            get {
                return ResourceManager.GetString("PLAN_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string PLAN_Step4 {
            get {
                return ResourceManager.GetString("PLAN_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisar e Salvar.
        /// </summary>
        public static string PLAN_Step5 {
            get {
                return ResourceManager.GetString("PLAN_Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo do Plano.
        /// </summary>
        public static string PLAN_SummaryTitle {
            get {
                return ResourceManager.GetString("PLAN_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot.
        /// </summary>
        public static string PLAN_Total {
            get {
                return ResourceManager.GetString("PLAN_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taj.
        /// </summary>
        public static string PLAN_TotalA {
            get {
                return ResourceManager.GetString("PLAN_TotalA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód Produto.
        /// </summary>
        public static string PRODUCT_Code {
            get {
                return ResourceManager.GetString("PRODUCT_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Produto.
        /// </summary>
        public static string PRODUCT_Create {
            get {
                return ResourceManager.GetString("PRODUCT_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Produto.
        /// </summary>
        public static string PRODUCT_Edit {
            get {
                return ResourceManager.GetString("PRODUCT_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string PRODUCT_List {
            get {
                return ResourceManager.GetString("PRODUCT_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cx Emb.
        /// </summary>
        public static string PRODUCT_PackSize {
            get {
                return ResourceManager.GetString("PRODUCT_PackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Produto.
        /// </summary>
        public static string PRODUCTCATEGORY {
            get {
                return ResourceManager.GetString("PRODUCTCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Tipo de Produto.
        /// </summary>
        public static string PRODUCTCATEGORY_Create {
            get {
                return ResourceManager.GetString("PRODUCTCATEGORY_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tipo de Produto.
        /// </summary>
        public static string PRODUCTCATEGORY_Edit {
            get {
                return ResourceManager.GetString("PRODUCTCATEGORY_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Produto.
        /// </summary>
        public static string PRODUCTCATEGORY_List {
            get {
                return ResourceManager.GetString("PRODUCTCATEGORY_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumário do Ciclo.
        /// </summary>
        public static string REPORT_Summary {
            get {
                return ResourceManager.GetString("REPORT_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.V..
        /// </summary>
        public static string SALESFORCE {
            get {
                return ResourceManager.GetString("SALESFORCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR.
        /// </summary>
        public static string SEARCH_Go {
            get {
                return ResourceManager.GetString("SEARCH_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar....
        /// </summary>
        public static string SEARCH_Placeholder {
            get {
                return ResourceManager.GetString("SEARCH_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Início.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string STATUS_Active {
            get {
                return ResourceManager.GetString("STATUS_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string STATUS_Inactive {
            get {
                return ResourceManager.GetString("STATUS_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação foi concluída com sucesso!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ajustado.
        /// </summary>
        public static string TOTALA {
            get {
                return ResourceManager.GetString("TOTALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
